### ISSUE TITLE
markdownweb table

### ISSUE THREAD

**Issue by cbcinc** [jgauffin/markdownweb#1]
After the last update, the table does not work anymore. everything following the table syntax is included inside the table, meaning the rest of the page will be inside a table.
### Liste des paquets Nuget pour IvFragment Secondaire N3.

| Nom | Version | Descriptions |
| --- | --- | --- |
| N3_IVFragment_Secondaire_MVC5 | 1.2.1 | Utilitaires pour les fragments secondaire |
### N3 IvFragment Secondaire MVC5

> Ce paquet Nuget intégrera les fichiers utilitaires requis pour aider à convertir une section d'application .NET MVC en fragment secondaire.
> Quelques modifications seront exécutées dans le fichier de config pour installer le filtre N3 pour le fragment secondaire.

![image](https://cloud.githubusercontent.com/assets/10774173/5977134/0b3bfc66-a863-11e4-805b-a55f218f3b41.png)

The result code is like below; it is missing a th closing tag and merge the rest of the document in the table.

```
<h3 id="ListedespaquetsNugetpourIvFragmentSecondaireN3">Liste des paquets Nuget pour IvFragment Secondaire N3.</h3>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th><p>Nom</th>
<th>Version</th>
<th>Descriptions
</tr>
</thead>
<tbody>
<tr>
<td>N3 IVFragment Secondaire_MVC5</td>
<td>1.2.1</td>
<td>Utilitaires pour les fragments secondaire</p></td>
</tr>

The following portion should not have been included in the table.

<tr><td><h3 id="N3IvFragmentSecondaireMVC5">N3 IvFragment Secondaire MVC5</h3></td></tr>
<tr><td><blockquote></td></tr>
<tr><td><p>Ce paquet Nuget intégrera les fichiers utilitaires requis pour aider à convertir une section d'application .NET MVC en fragment secondaire.</td></tr>
<tr><td>Quelques modifications seront exécutées dans le fichier de config pour installer le filtre N3 pour le fragment secondaire.</p></td></tr>
<tr><td></blockquote></td></tr>
<tr><td><h4 id="Action">Action</h4></td></tr>
<tr><td><blockquote></td></tr>
<tr><td><p><a href="/doc/IvFragment">Retourer au menu principal de IvFragment Secondaire N3</a></p></td></tr>
<tr><td><p><a href="/">Retourer au menu principal</a></p></td></tr>
<tr><td></blockquote></td></tr>
</tbody></table>
```

**Comment by jgauffin** [comment]
Did you try with the nuget package or the source?

This test works: https://github.com/jgauffin/markdownweb/blob/master/src/MarkdownWeb.Tests/GithubIssues.cs

**Comment by cbcinc** [comment]
I Try the Nuget package.

I revert back to my prior version 1.0.1 and it is ok now.

The new version is not working on my side regarding table.

Merci.

Carl Barbeau

Carl Barbeau Consultants Inc.

Tel: 450-964-4311

Cel: 514-893-9224

 mailto:carl@cb-cinc.com carl@cb-cinc.com

 http://www.linkedin.com/redir/redirect?url=http%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fpub%2Fcarl-barbeau%2F7%2F778%2F415&urlhash=uBl5 http://www.linkedin.com/pub/carl-barbeau/7/778/415

 http://ca.linkedin.com/pub/carl-barbeau/7/778/415 Voir mon profil sur LinkedIn

**Comment by jgauffin** [comment]
How about now?
