### ISSUE TITLE
MarkdownWeb has the features I need, but not the api

### ISSUE THREAD

**Issue by thomaseyde** [jgauffin/markdownweb#2]
I have my own markdown document as an embedded resource, and all I need is to parse it to html. But the given api is coupled to the file system, which is irrelevant to me. I can't pass nulls either.

If only something like were available:

```
var html = Markdown.ToHtml(markdown);
```

**Comment by jgauffin** [comment]
I just commited a new version which can be used as you like. However, this project isn't just about parsing strings so you need to do a bit extra to make it possible.

Use the `PageService.ParseString` method.  `PageService` requires a repository as a dependency, but you do not really need to implement it (just return empty objects and empty strings from it).
